services:
  qdrant-test:
    image: qdrant/qdrant:latest
    container_name: qdrant-test
    ports:
      - "6333:6333"
    volumes:
      - qdrant_test_data:/qdrant/storage
    restart: unless-stopped

  ollama-rag-test:
    image: ollama/ollama
    container_name: ollama-rag-test
    ports:
      - "11435:11434"
    volumes:
      - ollama_test_data:/root/.ollama
    restart: unless-stopped

  rag-api-test:
    build: .
    container_name: rag-api-test
    ports:
      - "8001:8000"
    environment:
      RAG_ENV_NAME: test
      RAG_QDRANT_URL: http://qdrant-test:6333
      RAG_COLLECTION_NAME: rag_test
      RAG_DOCS_PATH: data/test/sample_docs.txt
      RAG_OLLAMA_URL: http://ollama-rag-test:11434
      RAG_OLLAMA_MODEL: llama3.2:1b
    depends_on:
      - qdrant-test
      - ollama-rag-test
    restart: unless-stopped

volumes:
  qdrant_test_data:
  ollama_test_data: